routes/web.php
Route::get('/local/{locale}', 'FrontLocalController@setLang');

Route::get('fb-login/{provider}', 'Auth\LoginController@redirectToProvider')->name('social.login');
Route::get('fb-login/{provider}/callback', 'Auth\LoginController@handleProviderCallback');

Route::any('/', 'Front\FrontController@index');
Route::get('/about', 'Front\FrontController@about');

Route::any('/all-docs/{cat_id}', 'Front\FrontController@allDocs');
Route::get('/fetch-docs/{cat_id}', 'Front\FrontController@fetchDocs');
Route::any('/doc/institutional/{doc_id}/institute/{inst_id}', 'Front\FrontController@docInstitutional');

Route::get('/doc/fetch-institutional/{doc_id}/institute/{inst_id}', 'Front\FrontController@fetch_institutional');

Route::any('/doc/by_article/{doc_id}/article/{article_id}', 'Front\FrontController@docByArticle');
Route::get('/fetch-article/{doc_id}/{article_id}', 'Front\FrontController@fetchArticle');

Route::any('/doc/by_article/{doc_id}/article/{article_id}/hide', 'Front\FrontController@docByArticle2');

Route::any('/library', 'Front\LibraryController@index');
Route::get('/library/fetch-doctrines/{razdel_id}', 'Front\LibraryController@fetch_doctrines');
Route::get('/library/{razdel_id}/doctrine/{doctrine_id}', 'Front\LibraryController@doctrinePage');
Route::get('/library/razdel/{razdel_id}/doctrine/{doctrine_id}', 'Front\LibraryController@doctrinePage2');

//All AJAX ROUTES
Route::post('/get_discussion', 'Front\FrontController@getDiscussion');
Route::post('/get_discussion_by_article', 'Front\DiscussionController@getDiscussionArticle');
Route::post('/get_contra_positions', 'Front\FrontController@getContraPositions');
Route::post('/get_compare_box_jurisdictions', 'Front\FrontController@getCompareBoxJurisdictions');
Route::post('/get_compare_box_institute', 'Front\FrontController@getCompareBoxInstitute');
Route::post('/get_compare_box_new', 'Front\FrontController@getCompareBoxNew');
Route::post('/get_doctrine', 'Front\FrontController@getDoctrine');
Route::post('/get_discussion_suggestion', 'Front\DiscussionController@getDiscussionSuggestions');
Route::post('/get_contra_positions_suggestions', 'Front\DiscussionController@getContraPositionsSuggestions');

Route::any('/error/{err_id}', 'Front\FrontController@error');

Route::any('/load_doctrine/{pos_id}', 'Front\FrontController@loadDoctrine');

//END ALL AJAX ROUTES

Route::group(['middleware' => ['authruslan']],
    function(){
    Route::any('/cabinet', 'Front\FrontController@cabinet')->name('cabinet');
    Route::post('/logout', 'Front\LoginController@logout')->name('logout');
    Route::any('/cabinet/positions', 'Front\FrontController@cabinetPositions');
    Route::resource('user', 'Front\FrontController');
    Route::post('/add_position', 'Front\FrontController@addPosition');
    Route::post('/edit_position', 'Front\FrontController@editPosition');
    Route::post('/add_comment', 'Front\FrontController@addComment');
});

Route::any('/team', 'Front\FrontController@Team');
Route::any('/base_docs', 'Front\FrontController@baseDocs');
Route::any('/faqs', 'Front\FrontController@Faqs');

Route::any('/loginform', 'Front\FrontController@loginForm')->name('loginform');
Route::any('/registration_form', 'Front\FrontController@registrationForm');
Route::any('/wall/{u_id}', 'Front\FrontController@publicProfile');

Route::any('/select2/institutes/{npa_id}', 'Front\FrontController@select2Institutes');
Route::any('/select2/npas', 'Front\FrontController@select2Npas');
Route::any('/inses_to_search/{npa_id}', 'Front\FrontController@insesToSearch');

Route::post('/front_register_post', 'Front\FrontController@frontReg');
Route::post('/reg/media', 'Front\FrontController@storeMedia')->name('front.reg.storeMedia');
Route::post('/front_login', 'Front\FrontController@frontLogin');



Route::get('/home', function () {
    if (session('status')) {
        return redirect()->route('admin.home')->with('status', session('status'));
    }

    return redirect()->route('admin.home');
});


Route::any('/select2/institutes_parent/{npa_id}', 'Admin\InstitutesController@select2InstitutesParent');
Route::any('/select2/institutes/{npa_id}', 'Admin\InstitutesController@select2Institutes');
Route::any('/select2/rules/{npa_id}', 'Admin\RulesController@select2Rules');

Auth::routes();
// Admin

Route::group(['prefix' => 'admin', 'as' => 'admin.', 'namespace' => 'Admin', 'middleware' => ['auth']], function () {
    Route::get('/', 'HomeController@index')->name('home');
    // Permissions
    Route::delete('permissions/destroy', 'PermissionsController@massDestroy')->name('permissions.massDestroy');
    Route::resource('permissions', 'PermissionsController');

    // Roles
    Route::delete('roles/destroy', 'RolesController@massDestroy')->name('roles.massDestroy');
    Route::resource('roles', 'RolesController');

    // Users
    Route::delete('users/destroy', 'UsersController@massDestroy')->name('users.massDestroy');
    Route::post('users/media', 'UsersController@storeMedia')->name('users.storeMedia');
    Route::post('users/ckmedia', 'UsersController@storeCKEditorImages')->name('users.storeCKEditorImages');
    Route::resource('users', 'UsersController');

    // Organizations
    Route::delete('organizations/destroy', 'OrganizationsController@massDestroy')->name('organizations.massDestroy');
    Route::resource('organizations', 'OrganizationsController');

    // Npas
    Route::delete('npas/destroy', 'NpaController@massDestroy')->name('npas.massDestroy');
    Route::resource('npas', 'NpaController');

    // Institutes
    Route::delete('institutes/destroy', 'InstitutesController@massDestroy')->name('institutes.massDestroy');
    Route::resource('institutes', 'InstitutesController');

    Route::post('update-numeration', 'InstitutesController@updateNumeration')->name('update-numeration');


    Route::get('about', 'AboutController@edit')->name('about.edit');
    Route::post('about/update', 'AboutController@update')->name('about.update');

    // Discusses
    Route::delete('discusses/destroy', 'DiscussController@massDestroy')->name('discusses.massDestroy');
    Route::post('discusses/media', 'DiscussController@storeMedia')->name('discusses.storeMedia');
    Route::post('discusses/ckmedia', 'DiscussController@storeCKEditorImages')->name('discusses.storeCKEditorImages');
    Route::resource('discusses', 'DiscussController');

    // Law Systems
    Route::delete('law-systems/destroy', 'LawSystemController@massDestroy')->name('law-systems.massDestroy');
    Route::post('law-systems/media', 'LawSystemController@storeMedia')->name('law-systems.storeMedia');
    Route::post('law-systems/ckmedia', 'LawSystemController@storeCKEditorImages')->name('law-systems.storeCKEditorImages');
    Route::resource('law-systems', 'LawSystemController');


    // Positions
    Route::delete('positions/destroy', 'PositionsController@massDestroy')->name('positions.massDestroy');
    Route::post('positions/media', 'PositionsController@storeMedia')->name('positions.storeMedia');
    Route::post('positions/ckmedia', 'PositionsController@storeCKEditorImages')->name('positions.storeCKEditorImages');
    Route::resource('positions', 'PositionsController');

    // Arguments
    Route::delete('arguments/destroy', 'ArgumentsController@massDestroy')->name('arguments.massDestroy');
    Route::post('arguments/media', 'ArgumentsController@storeMedia')->name('arguments.storeMedia');
    Route::post('arguments/ckmedia', 'ArgumentsController@storeCKEditorImages')->name('arguments.storeCKEditorImages');
    Route::resource('arguments', 'ArgumentsController');

    // Categories
    Route::delete('categories/destroy', 'CategoryController@massDestroy')->name('categories.massDestroy');
    Route::resource('categories', 'CategoryController');

    // Articles
    Route::delete('articles/destroy', 'ArticleController@massDestroy')->name('articles.massDestroy');
    Route::post('articles/media', 'ArticleController@storeMedia')->name('articles.storeMedia');
    Route::post('articles/ckmedia', 'ArticleController@storeCKEditorImages')->name('articles.storeCKEditorImages');
    Route::resource('articles', 'ArticleController');

    // Rules
    Route::delete('rules/destroy', 'RulesController@massDestroy')->name('rules.massDestroy');
    Route::post('rules/media', 'RulesController@storeMedia')->name('rules.storeMedia');
    Route::post('rules/ckmedia', 'RulesController@storeCKEditorImages')->name('rules.storeCKEditorImages');
    Route::resource('rules', 'RulesController');

    // Suggestions
    Route::delete('suggestions/destroy', 'SuggestionsController@massDestroy')->name('suggestions.massDestroy');
    Route::post('suggestions/media', 'SuggestionsController@storeMedia')->name('suggestions.storeMedia');
    Route::post('suggestions/ckmedia', 'SuggestionsController@storeCKEditorImages')->name('suggestions.storeCKEditorImages');
    Route::resource('suggestions', 'SuggestionsController');

    // Razdels
    Route::delete('razdels/destroy', 'RazdelsController@massDestroy')->name('razdels.massDestroy');
    Route::resource('razdels', 'RazdelsController');

    // Doctrines
    Route::delete('doctrines/destroy', 'DoctrineController@massDestroy')->name('doctrines.massDestroy');
    Route::post('doctrines/media', 'DoctrineController@storeMedia')->name('doctrines.storeMedia');
    Route::post('doctrines/ckmedia', 'DoctrineController@storeCKEditorImages')->name('doctrines.storeCKEditorImages');
    Route::resource('doctrines', 'DoctrineController');

    // Normats
    Route::delete('normats/destroy', 'NormatController@massDestroy')->name('normats.massDestroy');
    Route::post('normats/media', 'NormatController@storeMedia')->name('normats.storeMedia');
    Route::post('normats/ckmedia', 'NormatController@storeCKEditorImages')->name('normats.storeCKEditorImages');
    Route::resource('normats', 'NormatController');

    // Courts
    Route::delete('courts/destroy', 'CourtController@massDestroy')->name('courts.massDestroy');

app/Http/Controllers/Admin/NpaController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Requests\MassDestroyNpaRequest;
use App\Http\Requests\StoreNpaRequest;
use App\Http\Requests\UpdateNpaRequest;
use App\Models\Category;
use App\Models\Npa;
use App\Models\Organization;
use Gate;
use Illuminate\Http\Request;
use Symfony\Component\HttpFoundation\Response;
use Yajra\DataTables\Facades\DataTables;
use Auth;

class NpaController extends Controller
{
    public function index(Request $request)
    {
        abort_if(Gate::denies('npa_access'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        if ($request->ajax()){
            if(Auth::user()->roles->contains(2) || Auth::user()->roles->contains(5)){
                $query = Npa::where('organization_id', Auth::user()->organization_id)->with(['category', 'organization'])->select(sprintf('%s.*', (new Npa)->table));
            }
            else{
                $query = Npa::with(['category', 'organization'])->select(sprintf('%s.*', (new Npa)->table));
            }
            
            $table = Datatables::of($query);

            $table->addColumn('placeholder', '&nbsp;');
            $table->addColumn('actions', '&nbsp;');

            $table->editColumn('actions', function ($row) {
                $viewGate      = 'npa_show';
                $editGate      = 'npa_edit';
                $deleteGate    = 'npa_delete';
                $crudRoutePart = 'npas';

                return view('partials.datatablesActions', compact(
                    'viewGate',
                    'editGate',
                    'deleteGate',
                    'crudRoutePart',
                    'row'
                ));
            });

            $table->editColumn('id', function ($row) {
                return $row->id ? $row->id : "";
            });
            $table->editColumn('name', function ($row) {
                return $row->name ? $row->name : "";
            });
            $table->editColumn('pod_name', function ($row) {
                return $row->pod_name ? $row->pod_name : "";
            });
            $table->addColumn('category_name', function ($row) {
                return $row->category ? $row->category->name : '';
            });

            $table->editColumn('type', function ($row) {
                return $row->type ? Npa::TYPE_SELECT[$row->type] : '';
            });
            $table->addColumn('organization_name', function ($row) {
                return $row->organization ? $row->organization->name : '';
            });

            $table->rawColumns(['actions', 'placeholder', 'category', 'organization']);

            return $table->make(true);
        }

        return view('admin.npas.index');
    }

    public function create()
    {
        abort_if(Gate::denies('npa_create'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $categories = Category::all()->pluck('name', 'id')->prepend(trans('global.pleaseSelect'), '');

        $organizations = Organization::all()->pluck('name', 'id')->prepend(trans('global.pleaseSelect'), '');

        return view('admin.npas.create', compact('categories', 'organizations'));
    }

    public function store(StoreNpaRequest $request)
    {
        $npa = Npa::create($request->all());
        $npa->setTranslation('name', 'ru', $request->input('name'))
                 ->setTranslation('name', 'kz', $request->input('name_kz'))
                 ->setTranslation('pod_name', 'ru', $request->input('pod_name'))
                 ->setTranslation('pod_name', 'kz', $request->input('pod_name_kz'))
                 ->save();

        return redirect()->route('admin.npas.index');
    }

    public function edit(Npa $npa)
    {
        abort_if(Gate::denies('npa_edit'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        if(auth()->user()->roles->contains(2) && auth()->user()->organization_id != $npa->organization_id){
            return "Вы не можете редактировать НПА, не принадлежащие Вашей организации";
        }

        $categories = Category::all()->pluck('name', 'id')->prepend(trans('global.pleaseSelect'), '');

        $organizations = Organization::all()->pluck('name', 'id')->prepend(trans('global.pleaseSelect'), '');

        $npa->load('category', 'organization');

        return view('admin.npas.edit', compact('categories', 'organizations', 'npa'));
    }

    public function update(UpdateNpaRequest $request, Npa $npa)
    {
        $npa->update($request->all());
        $npa->setTranslation('name', 'ru', $request->input('name'))
                 ->setTranslation('name', 'kz', $request->input('name_kz'))
                 ->setTranslation('pod_name', 'ru', $request->input('pod_name'))
                 ->setTranslation('pod_name', 'kz', $request->input('pod_name_kz'))
                 ->save();

        return redirect()->route('admin.npas.index');
    }

    public function show(Npa $npa)
    {
        abort_if(Gate::denies('npa_show'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        if(auth()->user()->roles->contains(2) && auth()->user()->organization_id != $npa->organization_id){
            return "Вы не можете просматривать НПА, не принадлежащие Вашей организации";
        }

        if(auth()->user()->roles->contains(5) && auth()->user()->organization_id != $npa->organization_id){
            return "Вы не можете просматривать НПА, не принадлежащие Вашей организации";
        }

        $npa->load('category', 'organization', 'npaInstitutes');

        return view('admin.npas.show', compact('npa'));
    }

    public function destroy(Npa $npa)
    {
        abort_if(Gate::denies('npa_delete'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        if(auth()->user()->roles->contains(2) && auth()->user()->organization_id != $npa->organization_id){
            return "Вы не можете удалять НПА, не принадлежащие Вашей организации";
        }

        $npa->delete();

        return back();
    }

    public function massDestroy(MassDestroyNpaRequest $request)
    {
        Npa::whereIn('id', request('ids'))->delete();

        return response(null, Response::HTTP_NO_CONTENT);
    }
}

resources/views/admin/npas/relationships/npaInstitutes.blade.php
@can('institute_create')
    <div style="margin-bottom: 10px;" class="row">
        <div class="col-lg-12">
            <a class="btn btn-success" href="{{ route('admin.institutes.create') }}">
                {{ trans('global.add') }} {{ trans('cruds.institute.title_singular') }}
            </a>
        </div>
    </div>
@endcan

<div class="card">
    <div class="card-header">
        {{ trans('cruds.institute.title_singular') }} {{ trans('global.list') }}
    </div>

    <div class="card-body">
        <div class="table-responsive">
            <table class=" table table-bordered table-striped table-hover datatable datatable-npaInstitutes">
                <thead>
                    <tr>
                        <th width="10">

                        </th>
                        <th>
                            {{ trans('cruds.institute.fields.id') }}
                        </th>
                        <th>
                            {{ trans('cruds.institute.fields.name') }}
                        </th>
                        <th>
                            {{ trans('cruds.institute.fields.npa') }}
                        </th>
                        <th>
                            {{ trans('cruds.institute.fields.parent_institute') }}
                        </th>
                        <th>
                            {{ trans('cruds.institute.fields.type') }}
                        </th>
                        <th>
                            &nbsp;
                        </th>
                    </tr>
                </thead>
                <tbody>
                    @foreach($institutes as $key => $institute)
                        <tr data-entry-id="{{ $institute->id }}">
                            <td>

                            </td>
                            <td>
                                {{ $institute->id ?? '' }}
                            </td>
                            <td>
                                {{ $institute->name ?? '' }}
                            </td>
                            <td>
                                {{ $institute->npa->name ?? '' }}
                            </td>
                            <td>
                                {{ $institute->parent_institute->name ?? '' }}
                            </td>
                            <td>
                                {{ App\Models\Institute::TYPE_SELECT[$institute->type] ?? '' }}
                            </td>
                            <td>
                                @can('institute_show')
                                    <a class="btn btn-xs btn-primary" href="{{ route('admin.institutes.show', $institute->id) }}">
                                        {{ trans('global.view') }}
                                    </a>
                                @endcan

                                @can('institute_edit')
                                    <a class="btn btn-xs btn-info" href="{{ route('admin.institutes.edit', $institute->id) }}">
                                        {{ trans('global.edit') }}
                                    </a>
                                @endcan

                                @can('institute_delete')
                                    <form action="{{ route('admin.institutes.destroy', $institute->id) }}" method="POST" onsubmit="return confirm('{{ trans('global.areYouSure') }}');" style="display: inline-block;">
                                        <input type="hidden" name="_method" value="DELETE">
                                        <input type="hidden" name="_token" value="{{ csrf_token() }}">
                                        <input type="submit" class="btn btn-xs btn-danger" value="{{ trans('global.delete') }}">
                                    </form>
                                @endcan

                            </td>

                        </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
    </div>
</div>

@section('scripts')
@parent
<script>
    $(function () {
  let dtButtons = $.extend(true, [], $.fn.dataTable.defaults.buttons)
@can('institute_delete')
  let deleteButtonTrans = '{{ trans('global.datatables.delete') }}'
  let deleteButton = {
    text: deleteButtonTrans,
    url: "{{ route('admin.institutes.massDestroy') }}",
    className: 'btn-danger',
    action: function (e, dt, node, config) {
      var ids = $.map(dt.rows({ selected: true }).nodes(), function (entry) {
          return $(entry).data('entry-id')
      });

      if (ids.length === 0) {
        alert('{{ trans('global.datatables.zero_selected') }}')

        return
      }

      if (confirm('{{ trans('global.areYouSure') }}')) {
        $.ajax({
          headers: {'x-csrf-token': _token},
          method: 'POST',
          url: config.url,
          data: { ids: ids, _method: 'DELETE' }})
          .done(function () { location.reload() })
      }
    }
  }
  dtButtons.push(deleteButton)
@endcan

  $.extend(true, $.fn.dataTable.defaults, {
    orderCellsTop: true,
    order: [[ 1, 'desc' ]],
    pageLength: 50,
  });
  let table = $('.datatable-npaInstitutes:not(.ajaxTable)').DataTable({ buttons: dtButtons })
  $('a[data-toggle="tab"]').on('shown.bs.tab click', function(e){
      $($.fn.dataTable.tables(true)).DataTable()
          .columns.adjust();
  });
  
})

</script>
@endsection