routes/web.php
<?php

Route::get('/settrans/{model}/{table}/{field}/{password}', 'FrontLocalController@ruslanSetLocal');

Route::get('/local/{locale}', 'FrontLocalController@setLang');

Route::get('fb-login/{provider}', 'Auth\LoginController@redirectToProvider')->name('social.login');
Route::get('fb-login/{provider}/callback', 'Auth\LoginController@handleProviderCallback');

Route::any('/', 'Front\FrontController@index');
Route::get('/about', 'Front\FrontController@about');

Route::any('/all-docs/{cat_id}', 'Front\FrontController@allDocs');
Route::get('/fetch-docs/{cat_id}', 'Front\FrontController@fetchDocs');
Route::any('/doc/institutional/{doc_id}/institute/{inst_id}', 'Front\FrontController@docInstitutional');

Route::get('/doc/fetch-institutional/{doc_id}/institute/{inst_id}', 'Front\FrontController@fetch_institutional');

Route::any('/doc/by_article/{doc_id}/article/{article_id}', 'Front\FrontController@docByArticle');
Route::get('/fetch-article/{doc_id}/{article_id}', 'Front\FrontController@fetchArticle');

Route::any('/doc/by_article/{doc_id}/article/{article_id}/hide', 'Front\FrontController@docByArticle2');

Route::any('/library', 'Front\LibraryController@index');
Route::get('/library/fetch-doctrines/{razdel_id}', 'Front\LibraryController@fetch_doctrines');
Route::get('/library/{razdel_id}/doctrine/{doctrine_id}', 'Front\LibraryController@doctrinePage');
Route::get('/library/razdel/{razdel_id}/doctrine/{doctrine_id}', 'Front\LibraryController@doctrinePage2');

//All AJAX ROUTES
Route::post('/get_discussion', 'Front\FrontController@getDiscussion');
Route::post('/get_discussion_by_article', 'Front\DiscussionController@getDiscussionArticle');
Route::post('/get_contra_positions', 'Front\FrontController@getContraPositions');
Route::post('/get_compare_box_jurisdictions', 'Front\FrontController@getCompareBoxJurisdictions');
Route::post('/get_compare_box_institute', 'Front\FrontController@getCompareBoxInstitute');
Route::post('/get_compare_box_new', 'Front\FrontController@getCompareBoxNew');
Route::post('/get_doctrine', 'Front\FrontController@getDoctrine');
Route::post('/get_discussion_suggestion', 'Front\DiscussionController@getDiscussionSuggestions');
Route::post('/get_contra_positions_suggestions', 'Front\DiscussionController@getContraPositionsSuggestions');

Route::any('/error/{err_id}', 'Front\FrontController@error');

Route::any('/load_doctrine/{pos_id}', 'Front\FrontController@loadDoctrine');

//END ALL AJAX ROUTES

Route::group(['middleware' => ['authruslan']],
    function(){
    Route::any('/cabinet', 'Front\FrontController@cabinet')->name('cabinet');
    Route::post('/logout', 'Front\LoginController@logout')->name('logout');
    Route::any('/cabinet/positions', 'Front\FrontController@cabinetPositions');
    Route::resource('user', 'Front\FrontController');
    Route::post('/add_position', 'Front\FrontController@addPosition');
    Route::post('/edit_position', 'Front\FrontController@editPosition');
    Route::post('/add_comment', 'Front\FrontController@addComment');
});

Route::any('/team', 'Front\FrontController@Team');
Route::any('/base_docs', 'Front\FrontController@baseDocs');
Route::any('/faqs', 'Front\FrontController@Faqs');

Route::any('/loginform', 'Front\FrontController@loginForm')->name('loginform');
Route::any('/registration_form', 'Front\FrontController@registrationForm');
Route::any('/wall/{u_id}', 'Front\FrontController@publicProfile');

Route::any('/select2/institutes/{npa_id}', 'Front\FrontController@select2Institutes');
Route::any('/select2/npas', 'Front\FrontController@select2Npas');
Route::any('/inses_to_search/{npa_id}', 'Front\FrontController@insesToSearch');

Route::post('/front_register_post', 'Front\FrontController@frontReg');
Route::post('/reg/media', 'Front\FrontController@storeMedia')->name('front.reg.storeMedia');
Route::post('/front_login', 'Front\FrontController@frontLogin');



Route::get('/home', function () {
    if (session('status')) {
        return redirect()->route('admin.home')->with('status', session('status'));
    }

    return redirect()->route('admin.home');
});


Route::any('/select2/institutes_parent/{npa_id}', 'Admin\InstitutesController@select2InstitutesParent');
Route::any('/select2/institutes/{npa_id}', 'Admin\InstitutesController@select2Institutes');
Route::any('/select2/rules/{npa_id}', 'Admin\RulesController@select2Rules');

Auth::routes();
// Admin

Route::group(['prefix' => 'admin', 'as' => 'admin.', 'namespace' => 'Admin', 'middleware' => ['auth']], function () {
    Route::get('/', 'HomeController@index')->name('home');
    // Permissions
    Route::delete('permissions/destroy', 'PermissionsController@massDestroy')->name('permissions.massDestroy');
    Route::resource('permissions', 'PermissionsController');

    // Roles
    Route::delete('roles/destroy', 'RolesController@massDestroy')->name('roles.massDestroy');
    Route::resource('roles', 'RolesController');

    // Users
    Route::delete('users/destroy', 'UsersController@massDestroy')->name('users.massDestroy');
    Route::post('users/media', 'UsersController@storeMedia')->name('users.storeMedia');
    Route::post('users/ckmedia', 'UsersController@storeCKEditorImages')->name('users.storeCKEditorImages');
    Route::resource('users', 'UsersController');

    // Organizations
    Route::delete('organizations/destroy', 'OrganizationsController@massDestroy')->name('organizations.massDestroy');
    Route::resource('organizations', 'OrganizationsController');

    // Npas
    Route::delete('npas/destroy', 'NpaController@massDestroy')->name('npas.massDestroy');
    Route::resource('npas', 'NpaController');

    // Institutes
    Route::delete('institutes/destroy', 'InstitutesController@massDestroy')->name('institutes.massDestroy');
    Route::resource('institutes', 'InstitutesController');

    Route::post('update-numeration', 'InstitutesController@updateNumeration')->name('update-numeration');


    Route::get('about', 'AboutController@edit')->name('about.edit');
    Route::post('about/update', 'AboutController@update')->name('about.update');

    // Discusses
    Route::delete('discusses/destroy', 'DiscussController@massDestroy')->name('discusses.massDestroy');
    Route::post('discusses/media', 'DiscussController@storeMedia')->name('discusses.storeMedia');
    Route::post('discusses/ckmedia', 'DiscussController@storeCKEditorImages')->name('discusses.storeCKEditorImages');
    Route::resource('discusses', 'DiscussController');

    // Law Systems
    Route::delete('law-systems/destroy', 'LawSystemController@massDestroy')->name('law-systems.massDestroy');
    Route::post('law-systems/media', 'LawSystemController@storeMedia')->name('law-systems.storeMedia');
    Route::post('law-systems/ckmedia', 'LawSystemController@storeCKEditorImages')->name('law-systems.storeCKEditorImages');
    Route::resource('law-systems', 'LawSystemController');


    // Positions
    Route::delete('positions/destroy', 'PositionsController@massDestroy')->name('positions.massDestroy');
    Route::post('positions/media', 'PositionsController@storeMedia')->name('positions.storeMedia');
    Route::post('positions/ckmedia', 'PositionsController@storeCKEditorImages')->name('positions.storeCKEditorImages');
    Route::resource('positions', 'PositionsController');

    // Arguments
    Route::delete('arguments/destroy', 'ArgumentsController@massDestroy')->name('arguments.massDestroy');
    Route::post('arguments/media', 'ArgumentsController@storeMedia')->name('arguments.storeMedia');
    Route::post('arguments/ckmedia', 'ArgumentsController@storeCKEditorImages')->name('arguments.storeCKEditorImages');
    Route::resource('arguments', 'ArgumentsController');

    // Categories
    Route::delete('categories/destroy', 'CategoryController@massDestroy')->name('categories.massDestroy');
    Route::resource('categories', 'CategoryController');

    // Articles
    Route::delete('articles/destroy', 'ArticleController@massDestroy')->name('articles.massDestroy');
    Route::post('articles/media', 'ArticleController@storeMedia')->name('articles.storeMedia');
    Route::post('articles/ckmedia', 'ArticleController@storeCKEditorImages')->name('articles.storeCKEditorImages');
    Route::resource('articles', 'ArticleController');

    // Rules
    Route::delete('rules/destroy', 'RulesController@massDestroy')->name('rules.massDestroy');
    Route::post('rules/media', 'RulesController@storeMedia')->name('rules.storeMedia');
    Route::post('rules/ckmedia', 'RulesController@storeCKEditorImages')->name('rules.storeCKEditorImages');
    Route::resource('rules', 'RulesController');

    // Suggestions
    Route::delete('suggestions/destroy', 'SuggestionsController@massDestroy')->name('suggestions.massDestroy');
    Route::post('suggestions/media', 'SuggestionsController@storeMedia')->name('suggestions.storeMedia');
    Route::post('suggestions/ckmedia', 'SuggestionsController@storeCKEditorImages')->name('suggestions.storeCKEditorImages');
    Route::resource('suggestions', 'SuggestionsController');

    // Razdels
    Route::delete('razdels/destroy', 'RazdelsController@massDestroy')->name('razdels.massDestroy');
    Route::resource('razdels', 'RazdelsController');

    // Doctrines
    Route::delete('doctrines/destroy', 'DoctrineController@massDestroy')->name('doctrines.massDestroy');
    Route::post('doctrines/media', 'DoctrineController@storeMedia')->name('doctrines.storeMedia');
    Route::post('doctrines/ckmedia', 'DoctrineController@storeCKEditorImages')->name('doctrines.storeCKEditorImages');
    Route::resource('doctrines', 'DoctrineController');

    // Normats
    Route::delete('normats/destroy', 'NormatController@massDestroy')->name('normats.massDestroy');
    Route::post('normats/media', 'NormatController@storeMedia')->name('normats.storeMedia');
    Route::post('normats/ckmedia', 'NormatController@storeCKEditorImages')->name('normats.storeCKEditorImages');
    Route::resource('normats', 'NormatController');

    // Courts

app/Models/Article.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Spatie\MediaLibrary\HasMedia\HasMedia;
use Spatie\MediaLibrary\HasMedia\HasMediaTrait;
use Spatie\MediaLibrary\Models\Media;
use \DateTimeInterface;

class Article extends Model implements HasMedia
{
    use SoftDeletes, HasMediaTrait;

    public $table = 'articles';

    protected $dates = [
        'created_at',
        'updated_at',
        'deleted_at',
    ];

    protected $fillable = [
        'red_1',
        'created_at',
        'updated_at',
        'deleted_at',
    ];

    protected function serializeDate(DateTimeInterface $date)
    {
        return $date->format('Y-m-d H:i:s');
    }

    public function registerMediaConversions(Media $media = null)
    {
        $this->addMediaConversion('thumb')->fit('crop', 50, 50);
        $this->addMediaConversion('preview')->fit('crop', 120, 120);
    }
}

app/Http/Controllers/Admin/ArticleController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Controllers\Traits\MediaUploadingTrait;
use App\Http\Requests\MassDestroyArticleRequest;
use App\Http\Requests\StoreArticleRequest;
use App\Http\Requests\UpdateArticleRequest;
use App\Models\Article;
use Gate;
use Illuminate\Http\Request;
use Spatie\MediaLibrary\Models\Media;
use Symfony\Component\HttpFoundation\Response;

class ArticleController extends Controller
{
    use MediaUploadingTrait;

    public function index()
    {
        abort_if(Gate::denies('article_access'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $articles = Article::all();

        return view('admin.articles.index', compact('articles'));
    }

    public function create()
    {
        abort_if(Gate::denies('article_create'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        return view('admin.articles.create');
    }

    public function store(StoreArticleRequest $request)
    {
        $article = Article::create($request->all());

        if ($media = $request->input('ck-media', false)) {
            Media::whereIn('id', $media)->update(['model_id' => $article->id]);
        }

        return redirect()->route('admin.articles.index');
    }

    public function edit(Article $article)
    {
        abort_if(Gate::denies('article_edit'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        return view('admin.articles.edit', compact('article'));
    }

    public function update(UpdateArticleRequest $request, Article $article)
    {
        $article->update($request->all());

        return redirect()->route('admin.articles.index');
    }

    public function show(Article $article)
    {
        abort_if(Gate::denies('article_show'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        return view('admin.articles.show', compact('article'));
    }

    public function destroy(Article $article)
    {
        abort_if(Gate::denies('article_delete'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $article->delete();

        return back();
    }

    public function massDestroy(MassDestroyArticleRequest $request)
    {
        Article::whereIn('id', request('ids'))->delete();

        return response(null, Response::HTTP_NO_CONTENT);
    }

    public function storeCKEditorImages(Request $request)
    {
        abort_if(Gate::denies('article_create') && Gate::denies('article_edit'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $model         = new Article();
        $model->id     = $request->input('crud_id', 0);
        $model->exists = true;
        $media         = $model->addMediaFromRequest('upload')->toMediaCollection('ck-media');

        return response()->json(['id' => $media->id, 'url' => $media->getUrl()], Response::HTTP_CREATED);
    }
}

resources/views/admin/articles/create.blade.php
@extends('layouts.admin')
@section('content')

<div class="card">
    <div class="card-header">
        {{ trans('global.create') }} {{ trans('cruds.article.title_singular') }}
    </div>

    <div class="card-body">
        <form method="POST" action="{{ route("admin.articles.store") }}" enctype="multipart/form-data">
            @csrf
            <div class="form-group">
                <label for="red_1">{{ trans('cruds.article.fields.red_1') }}</label>
                <textarea class="form-control ckeditor {{ $errors->has('red_1') ? 'is-invalid' : '' }}" name="red_1" id="red_1">{!! old('red_1') !!}</textarea>
                @if($errors->has('red_1'))
                    <div class="invalid-feedback">
                        {{ $errors->first('red_1') }}
                    </div>
                @endif
                <span class="help-block">{{ trans('cruds.article.fields.red_1_helper') }}</span>
            </div>
            <div class="form-group">
                <button class="btn btn-danger" type="submit">
                    {{ trans('global.save') }}
                </button>
            </div>
        </form>
    </div>
</div>



@endsection

@section('scripts')
<script>
    $(document).ready(function () {
  function SimpleUploadAdapter(editor) {
    editor.plugins.get('FileRepository').createUploadAdapter = function(loader) {
      return {
        upload: function() {
          return loader.file
            .then(function (file) {
              return new Promise(function(resolve, reject) {
                // Init request
                var xhr = new XMLHttpRequest();
                xhr.open('POST', '/admin/articles/ckmedia', true);
                xhr.setRequestHeader('x-csrf-token', window._token);
                xhr.setRequestHeader('Accept', 'application/json');
                xhr.responseType = 'json';

                // Init listeners
                var genericErrorText = `Couldn't upload file: ${ file.name }.`;
                xhr.addEventListener('error', function() { reject(genericErrorText) });
                xhr.addEventListener('abort', function() { reject() });
                xhr.addEventListener('load', function() {
                  var response = xhr.response;

                  if (!response || xhr.status !== 201) {
                    return reject(response && response.message ? `${genericErrorText}\n${xhr.status} ${response.message}` : `${genericErrorText}\n ${xhr.status} ${xhr.statusText}`);
                  }

                  $('form').append('<input type="hidden" name="ck-media[]" value="' + response.id + '">');

                  resolve({ default: response.url });
                });

                if (xhr.upload) {
                  xhr.upload.addEventListener('progress', function(e) {
                    if (e.lengthComputable) {
                      loader.uploadTotal = e.total;
                      loader.uploaded = e.loaded;
                    }
                  });
                }

                // Send request
                var data = new FormData();
                data.append('upload', file);
                data.append('crud_id', {{ $article->id ?? 0 }});
                xhr.send(data);
              });
            })
        }
      };
    }
  }

  var allEditors = document.querySelectorAll('.ckeditor');
  for (var i = 0; i < allEditors.length; ++i) {
    ClassicEditor.create(
      allEditors[i], {
        extraPlugins: [SimpleUploadAdapter]
      }
    );
  }
});
</script>

@endsection

resources/views/admin/articles/edit.blade.php
@extends('layouts.admin')
@section('content')

<div class="card">
    <div class="card-header">
        {{ trans('global.edit') }} {{ trans('cruds.article.title_singular') }}
    </div>

    <div class="card-body">
        <form method="POST" action="{{ route("admin.articles.update", [$article->id]) }}" enctype="multipart/form-data">
            @method('PUT')
            @csrf
            <div class="form-group">
                <label for="red_1">{{ trans('cruds.article.fields.red_1') }}</label>
                <textarea class="form-control ckeditor {{ $errors->has('red_1') ? 'is-invalid' : '' }}" name="red_1" id="red_1">{!! old('red_1', $article->red_1) !!}</textarea>
                @if($errors->has('red_1'))
                    <div class="invalid-feedback">
                        {{ $errors->first('red_1') }}
                    </div>
                @endif
                <span class="help-block">{{ trans('cruds.article.fields.red_1_helper') }}</span>
            </div>
            <div class="form-group">
                <button class="btn btn-danger" type="submit">
                    {{ trans('global.save') }}
                </button>
            </div>
        </form>
    </div>
</div>



@endsection

@section('scripts')
<script>
    $(document).ready(function () {
  function SimpleUploadAdapter(editor) {
    editor.plugins.get('FileRepository').createUploadAdapter = function(loader) {
      return {
        upload: function() {
          return loader.file
            .then(function (file) {
              return new Promise(function(resolve, reject) {
                // Init request
                var xhr = new XMLHttpRequest();
                xhr.open('POST', '/admin/articles/ckmedia', true);
                xhr.setRequestHeader('x-csrf-token', window._token);
                xhr.setRequestHeader('Accept', 'application/json');
                xhr.responseType = 'json';

                // Init listeners
                var genericErrorText = `Couldn't upload file: ${ file.name }.`;
                xhr.addEventListener('error', function() { reject(genericErrorText) });
                xhr.addEventListener('abort', function() { reject() });
                xhr.addEventListener('load', function() {
                  var response = xhr.response;

                  if (!response || xhr.status !== 201) {
                    return reject(response && response.message ? `${genericErrorText}\n${xhr.status} ${response.message}` : `${genericErrorText}\n ${xhr.status} ${xhr.statusText}`);
                  }

                  $('form').append('<input type="hidden" name="ck-media[]" value="' + response.id + '">');

                  resolve({ default: response.url });
                });

                if (xhr.upload) {
                  xhr.upload.addEventListener('progress', function(e) {
                    if (e.lengthComputable) {
                      loader.uploadTotal = e.total;
                      loader.uploaded = e.loaded;
                    }
                  });
                }

                // Send request
                var data = new FormData();
                data.append('upload', file);
                data.append('crud_id', {{ $article->id ?? 0 }});
                xhr.send(data);
              });
            })
        }
      };
    }
  }

  var allEditors = document.querySelectorAll('.ckeditor');
  for (var i = 0; i < allEditors.length; ++i) {
    ClassicEditor.create(
      allEditors[i], {
        extraPlugins: [SimpleUploadAdapter]
      }
    );
  }
});
</script>

@endsection

resources/views/admin/articles/index.blade.php
@extends('layouts.admin')
@section('content')
@can('article_create')
    <div style="margin-bottom: 10px;" class="row">
        <div class="col-lg-12">
            <a class="btn btn-success" href="{{ route('admin.articles.create') }}">
                {{ trans('global.add') }} {{ trans('cruds.article.title_singular') }}
            </a>
        </div>
    </div>
@endcan
<div class="card">
    <div class="card-header">
        {{ trans('cruds.article.title_singular') }} {{ trans('global.list') }}
    </div>

    <div class="card-body">
        <div class="table-responsive">
            <table class=" table table-bordered table-striped table-hover datatable datatable-Article">
                <thead>
                    <tr>
                        <th width="10">

                        </th>
                        <th>
                            {{ trans('cruds.article.fields.id') }}
                        </th>
                        <th>
                            &nbsp;
                        </th>
                    </tr>
                </thead>
                <tbody>
                    @foreach($articles as $key => $article)
                        <tr data-entry-id="{{ $article->id }}">
                            <td>

                            </td>
                            <td>
                                {{ $article->id ?? '' }}
                            </td>
                            <td>
                                @can('article_show')
                                    <a class="btn btn-xs btn-primary" href="{{ route('admin.articles.show', $article->id) }}">
                                        {{ trans('global.view') }}
                                    </a>
                                @endcan

                                @can('article_edit')
                                    <a class="btn btn-xs btn-info" href="{{ route('admin.articles.edit', $article->id) }}">
                                        {{ trans('global.edit') }}
                                    </a>
                                @endcan

                                @can('article_delete')
                                    <form action="{{ route('admin.articles.destroy', $article->id) }}" method="POST" onsubmit="return confirm('{{ trans('global.areYouSure') }}');" style="display: inline-block;">
                                        <input type="hidden" name="_method" value="DELETE">
                                        <input type="hidden" name="_token" value="{{ csrf_token() }}">
                                        <input type="submit" class="btn btn-xs btn-danger" value="{{ trans('global.delete') }}">
                                    </form>
                                @endcan

                            </td>

                        </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
    </div>
</div>



@endsection
@section('scripts')
@parent
<script>
    $(function () {
  let dtButtons = $.extend(true, [], $.fn.dataTable.defaults.buttons)
@can('article_delete')
  let deleteButtonTrans = '{{ trans('global.datatables.delete') }}'
  let deleteButton = {
    text: deleteButtonTrans,
    url: "{{ route('admin.articles.massDestroy') }}",
    className: 'btn-danger',
    action: function (e, dt, node, config) {
      var ids = $.map(dt.rows({ selected: true }).nodes(), function (entry) {
          return $(entry).data('entry-id')
      });

      if (ids.length === 0) {
        alert('{{ trans('global.datatables.zero_selected') }}')

        return
      }

      if (confirm('{{ trans('global.areYouSure') }}')) {
        $.ajax({
          headers: {'x-csrf-token': _token},
          method: 'POST',
          url: config.url,
          data: { ids: ids, _method: 'DELETE' }})
          .done(function () { location.reload() })
      }
    }
  }
  dtButtons.push(deleteButton)
@endcan

  $.extend(true, $.fn.dataTable.defaults, {
    orderCellsTop: true,
    order: [[ 1, 'desc' ]],
    pageLength: 100,
  });
  let table = $('.datatable-Article:not(.ajaxTable)').DataTable({ buttons: dtButtons })
  $('a[data-toggle="tab"]').on('shown.bs.tab click', function(e){
      $($.fn.dataTable.tables(true)).DataTable()
          .columns.adjust();
  });
  
})

</script>
@endsection

resources/views/admin/articles/show.blade.php
@extends('layouts.admin')
@section('content')

<div class="card">
    <div class="card-header">
        {{ trans('global.show') }} {{ trans('cruds.article.title') }}
    </div>

    <div class="card-body">
        <div class="form-group">
            <div class="form-group">
                <a class="btn btn-default" href="{{ route('admin.articles.index') }}">
                    {{ trans('global.back_to_list') }}
                </a>
            </div>
            <table class="table table-bordered table-striped">
                <tbody>
                    <tr>
                        <th>
                            {{ trans('cruds.article.fields.id') }}
                        </th>
                        <td>
                            {{ $article->id }}
                        </td>
                    </tr>
                    <tr>
                        <th>
                            {{ trans('cruds.article.fields.red_1') }}
                        </th>
                        <td>
                            {!! $article->red_1 !!}
                        </td>
                    </tr>
                </tbody>
            </table>
            <div class="form-group">
                <a class="btn btn-default" href="{{ route('admin.articles.index') }}">
                    {{ trans('global.back_to_list') }}
                </a>
            </div>
        </div>
    </div>
</div>



@endsection